### ISSUE TITLE
The crash occurs in release mode.

### ISSUE THREAD

**Issue by maik-he** [MickeyHub/VideoPlayerContainer#11]
Hello, I am very interested in your library, which I find to be the best one I've used that supports SwiftUI. However, I noticed that when I run your demo in release mode, all the demo projects crash, whereas they work fine in debug mode.

**Comment by drsounds** [comment]
I am struggling with this too, as the app works excellent in dev mode in simulator and on my phone but always getting rejected on App Review and the snippet posted on GitHub is the same I get from Apple's crash report

**Comment by drsounds** [comment]
I think it is some kind of bug in release build targrt files causing some symbols not being correct in release target, as the error does not appear in debug

**Comment by drsounds** [comment]
Hi,
I've found that the culprint is an if let conditional below from PlayerWidget.swift page at line 123 are treated different if the build is release or debug, and according to ChatGPT this might occur due to code optimization. I've tried to disable all code optimizations but still error
````swift
if let feature = service.feature, case let .left(.squeeze(spacing)) = feature.direction { // in DEBUG mode this returns false, in RELEASE it returns true even if the service.feature is incomplete causing an sig error
                        
                        AnyView(
                            feature.content()
                                .frame(maxHeight: .infinity)
                                .transition(.move(edge: .leading))
                        )
                        
                        Spacer().frame(width: spacing)
                    }
````

**Comment by drsounds** [comment]
I've now forked this project and traced the offending thing to the conditional 
````swift
if let feature = service.feature
````
 which in debug returns false but true in release, and in both case shows nil value in inspector, so the problem might be in the @SyncState propertyWapper which construction might yield different results due to code optimization

**Comment by shayanbo** [comment]
Hi, @drsounds , Thanks for trying to fix this problem. I've removed the @StateSync propertyWrapper and manually sync state in the initializer of Service.

**Comment by drsounds** [comment]
I merged your changes to my branch of my fork of your repo, and it now works in release, now submitting the app to Apple and see what happens!

**Comment by shayanbo** [comment]
Great, you can attach the download URL here after it's approved.
