### ISSUE TITLE
It crashes when submitting to AppStore and TestFlight, but there is no crash when installed directly through xcode

### ISSUE THREAD

**Issue by Yyilin001** [MickeyHub/VideoPlayerContainer#13]
It crashes when submitting to AppStore and TestFlight, but there is no crash when installed directly through xcode

**Comment by Yyilin001** [comment]
This is the best library I have found for swift UI. I have embedded it into my application, but it crashed 100% when publishing, but I can't locate the problem because I am a I am new to development, but after I commented out the player-related code and submitted it to testFlight, everything went fine.

**Comment by Yyilin001** [comment]
public struct PlayerWidget: View {
    
    private weak var context: Context?
    
    /// Contructor for PlayerWidget
    ///
    /// - Parameter context: Context instance that's responsible for holding all of services.
    /// - Parameter launch: Optional Service Set needed to be created when PlayerWidget is created.
    /// - Returns: Instance of PlayerWidget
    /// - Attention:PlayerWidget is not responsible for maintaining Context lifecycle. developers should take on it. For example, take it as an @StateObject property in the enclosing View
    /
public init(_ context: Context, launch services: [Service.Type] = []) {
self.context = context

services.forEach { serviceType in
let _ = context[serviceType]
}
}

public var body: some View {

GeometryReader { proxy in

let _ = {
context?.viewSize.updateViewSize(proxy.size)
}()

WithService(PlayerService.self) { service in

HStack {

if let feature = service.feature, case let .left(.squeeze(spacing)) = feature.direction {

AnyView(
feature.content()
.frame(maxHeight: .infinity)
.transition(.move(edge: .leading))
)

Spacer().frame(width: spacing)
}




feature.content()   Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

**Comment by Yyilin001** [comment]
Edit scheme -> Build Configuration -> Release can reproduce this problem

**Comment by shayanbo** [comment]
Hi @Yyilin001 , sorry for being late. I think the latest commit of main branch has fixed this problem https://github.com/shayanbo/VideoPlayerContainer/issues/11 but didn't create a new tag for SPM. I just create a tag of 1.0.1, so you can update your dependency version and run it to see if it's working now.

**Comment by shayanbo** [comment]
https://github.com/shayanbo/VideoPlayerContainer/issues/11

**Comment by Yyilin001** [comment]
Thanks! That definitely fixed the issue.
