### ISSUE TITLE
Context instance keep a strong reference

### ISSUE THREAD

**Issue by JoeOCT91** [MickeyHub/VideoPlayerContainer#7]
Context instance keep a strong reference inside the player widget 

@main
struct ExampleApp: App {
    var body: some Scene {
        WindowGroup {
            NavigationStack {
                NavigationLink("Do some thing") {
                    ContentView()
                }

            }
        }
    }
}

when pop the content view the context, keep playing the video and  do not dealocate

**Comment by shayanbo** [comment]
Hi, @JoeOCT91 could you please upload your demo somewhere and paste the download link here? In this way, I can easily reproduce the bug you reported.

**Comment by shayanbo** [comment]
Thanks for filing this issue. the bug has been fixed in the latest commit.
