### ISSUE TITLE
How can I enter fullscreen mode on MacOS?

### ISSUE THREAD

**Issue by SilenceLove** [MickeyHub/VideoPlayerContainer#8]
[Original]
没有找到相关方法
[Translation]
I can't find the method

**Comment by shayanbo** [comment]
Hi, @SilenceLove . Actually, it's not this framework's responsibility. It's totally up to you to support the fullscreen mode. If you wanna check, you can follow this link: https://developer.apple.com/library/archive/documentation/General/Conceptual/MOSXAppProgrammingGuide/FullScreenApp/FullScreenApp.html
