### ISSUE TITLE
Is it possible to have just one Context that could be used by multiple PlayerWidget?

### ISSUE THREAD

**Issue by alexe100** [MickeyHub/VideoPlayerContainer#9]
Great widget!

Imagine an app screen with a List with 10 empty PlayerWidget (replaceCurrentItem was not called!) . Each empty PlayerWidget has assigned a String that stores the associated video Url. Then I can request to play any of the PlayerWidget one at a time.
In my implementation each PlayerWidget is created by passing a separated instantiated Context. When I want to play the first video, for example, I use the replaceCurrentItem method for the Context associated with the first PlayerWidget. Hence, If I want to present 10 empty PlayerWidgets ready to be played I have to instantiate 10 Context and pass each of them to the PlayerWidget related object.
My question is: Can I have 10 or 100 empty PlayerWidgets and have just one Context that is changed and assigned (during runtime) to a specific PlayerWidget to be able to play just that PlayerWidget?

Thank you

**Comment by shayanbo** [comment]
Thanks for your question. Actually, Context holds all of the player's states, if you share context, it means all of the PlayerWidgets with the same Context instance will act the same way (same action, same state).
In List, PlayerWidget will be reused, so you don't have to worry about the memory performance, there're a few PlayerWidgets and underlying Players (default is AVPlayer) in the memory.
